config/routes.rb
Rails.application.routes.draw do
  get 'admin', to: 'admin#index', as: :admin_page
  get 'books_users/buy/:id', to: 'books_users#buy', as: :books_users_buy
  get 'books_users/cancel/:id', to: 'books_users#cancel', as: :books_users_cancel
  resources :books
  root 'home#index'


  get 'home/profile', to: 'home#profile', as: :profile
  get 'home/index'
  get 'home/dashboard'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
    has_and_belongs_to_many :users
end

app/models/user.rb
class User < ApplicationRecord

  has_and_belongs_to_many :books
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable

validates :first_name, :last_name, presence: true, length: { maximum: 100, minimum: 3 }
validates :email, email: {mode: :strict}, length: { maximum: 150, minimum: 5 }

  def admin?
    role == "admin"
  end
end

app/models/usersbook.rb
class Usersbook < ApplicationRecord
  
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
    def index
      @books = Book.all
      authorize Book, policy_class: AdminPolicy
    rescue Pundit::NotAuthorizedError
      redirect_to root_path
    end
  end
  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit::Authorization
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
      devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
    end
 
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: %i[ new edit create update destroy ]

  def index
    @books = Book.all
  end

  def show
    @user_buy_current_book = user_signed_in? && current_user.books.where(id: params[:id]).any?
  end

  def new
    @book = Book.new
    authorize @book
  rescue Pundit::NotAuthorizedError
    redirect_to root_path
  end

  def edit
    authorize @book
  rescue Pundit::NotAuthorizedError
    redirect_to root_path
  end

  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to :admin_page, notice: "Книга была успешно создана." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to :admin_page, notice: "Книга был успешно обновлена." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    begin
      authorize @book
    rescue Pundit::NotAuthorizedError
      redirect_to root_path
      return
    end
    @book.destroy!

    respond_to do |format|
      format.html { redirect_to :admin_page, notice: "Книга была успешно удалена." }
      format.json { head :no_content }
    end
  end

  private

  def set_book
    @book = Book.find(params[:id])
  end

  def book_params
    params.require(:book).permit(:title, :description, :author, :price)
  end
end

app/controllers/books_users_controller.rb
class BooksUsersController < ApplicationController
    before_action :authenticate_user!
  
    def buy
      book = Book.find params[:id]
      unless current_user.books.where(id: params[:id]).any?
        current_user.books << book
      end
      redirect_to book
    end
  
    def cancel
      book = Book.find params[:id]
      if current_user.books.where(id: params[:id]).any?
        current_user.books.delete book.id
      end
      redirect_to book
    end
  end
  

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  before_action :authenticate_user!, only: [:profile]

  def index
    redirect_to books_path
  end

  def profile
    @current_user = current_user
    @books = current_user.books
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admin/index.html.erb
<%= link_to 'Главная', books_path %>

<h1>Админ</h1>

<%= link_to 'Новая книга', new_book_path %>

<h1>Все книги</h1>

<div id="books">
  <% @books.each do |book| %>
    <%= render book %>
    <p>
      <%= link_to "Подробнее", book %>
      <%= link_to "Редактировать", edit_book_path(book) %>
      <%= button_to "Удалить книгу", book, method: :delete %>
    </p>
  <% end %>
</div>

app/views/books/_book.html.erb
<div id="<%= dom_id book %>">
  <p>
    <strong>Название:</strong>
    <%= book.title %>
  </p>

  <p>
    <strong>Описание:</strong>
    <%= book.description %>
  </p>

  <p>
    <strong>Автор:</strong>
    <%= book.author %>
  </p>

  <p>
    <strong>Цена:</strong>
    <%= book.price %>
  </p>

</div>

app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
  

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :author, style: "display: block" %>
    <%= form.text_field :author %>
  </div>


  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>


  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Редактировать книгу</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Подробнее", @book %> |
  <%= link_to "Вернуться ко всем книгам", books_path %>

app/views/books/index.html.erb
<%= link_to 'Мой профиль', profile_path %>
<%= link_to 'Админ', :admin_page %>

<h1>Все книги</h1>

<div id="books">
  <% @books.each do |book| %>
    <%= render book %>
    <p>
      <%= link_to "Подробнее", book %>
    </p>
  <% end %>
</div>

app/views/books/new.html.erb
<h1>New book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Вернуться ко всем книгам", books_path %>
</div>

app/views/books/show.html.erb
<%= render @book %>

<div>
  <% if @user_buy_current_book %>
    <%= link_to "Вернуть", books_users_cancel_path(@book) %> |
  <% else %>
    <%= link_to "Купить", books_users_buy_path(@book) %> |
<% end %>
  <%= link_to "Вернуться ко всем книгам", books_path %>

</div>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>
<% if user_signed_in? %>Здравствуйте, <%= current_user.email %><%= link_to 'Выйти', destroy_user_session_path, data: { turbo_method: :delete } %>
<%= link_to 'Редактировать профиль', edit_user_registration_path %>
<% else %><%= link_to 'Войти', new_user_session_path %> или <%= link_to 'Зарегистрироваться', new_user_registration_path %>
<% end %>

<%= notice %>

<%= alert %>

app/views/home/profile.html.erb
<div class="profile">

  <%= link_to 'Главная', books_path %>

  <h1>Мой профиль</h1>

  <p>
    <strong>ФИО:</strong>
    <%= @current_user.first_name %> <%= @current_user.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= @current_user.email %>
  </p>

  <%= button_to "Выход", destroy_user_session_path, id: current_user.id, method: :delete, class:"delete" %>

  <h2>Мои купленные</h2>

  <div id="books">
    <% @books.each do |book| %>
      <%= render book %>
      <p>
        <%= link_to "Подробнее", book %>
      </p>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookvar</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>